### ISSUE TITLE
Backups publicly accessible

### ISSUE THREAD

**Issue by paul-hph** [nitsan-technologies/ns_backup#7]
is there a way to configure an alternative backup path? 
The default is publicly accessible, and i don't think that is a good idea.

**Comment by nitsan-technologies** [comment]
hey @paul-hph 

Thanks for reaching out! We definitely take security concerns seriously. You can learn how to configure a custom path to ensure it’s not publicly accessible by checking out this guide: [Backup Store Path Configuration](https://docs.t3planet.com/en/latest/ExtNsBackup/GlobalSettings/Index.html#backup-store-path).

If you have any further questions, feel free to let us know. We’re happy to help!

Cheers, Team NITSAN

**Comment by paul-hph** [comment]
That option is not available in the free version. And the default should be a secure path.

**Comment by nitsan-technologies** [comment]
Hey @paul-hph 

I appreciate your recommendation. We will check and consider reopening this ticket.

Cheers, Team NITSAN

**Comment by paul-hph** [comment]
it is also not available in the paid version: 

![image](https://github.com/user-attachments/assets/0282bd38-fd89-499a-bfab-31c0185a0044)

**Comment by nitsan-technologies** [comment]
Hey @paul-hph 

Which version do you have of `EXT:ns_backup` Could you please update the latest version? 

Cheers, Team NITSAN

**Comment by nitsan-technologies** [comment]
Hey @paul-hph 

You’re right! We’ve integrated this feature for TYPO3 v12. The good news is that our team has quickly added support for TYPO3 v11 as well. Please update to the latest version (v2.6.0) to get this feature on your TYPO3 v11.

If you need any further assistance, feel free to reach out. Thank you!

Cheers, Team NITSAN

**Comment by nitsan-technologies** [comment]
hey @paul-hph 

Good to hear, all works well. You'll need to run the Database analyser, You can find in-depth update version guidance at https://docs.t3planet.com/en/latest/License/UpdateVersion/Index.html

Cheers, Team NITSAN
